grands_prix = [
    {
        "name": "Australian Grand Prix",
        "id": 1254,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Chinese Grand Prix",
        "id": 1255,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Sprint Qualifying", "url_suffix": "sprint-qualifying"},
            {"type": "Sprint", "url_suffix": "sprint"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Japanese Grand Prix",
        "id": 1256,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Bahrain Grand Prix",
        "id": 1257,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Saudi Arabian Grand Prix",
        "id": 1258,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Miami Grand Prix",
        "id": 1259,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Sprint Qualifying", "url_suffix": "sprint-qualifying"},
            {"type": "Sprint", "url_suffix": "sprint"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Emilia Romagna Grand Prix",
        "id": 1260,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Monaco Grand Prix",
        "id": 1261,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Spanish Grand Prix",
        "id": 1262,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Canadian Grand Prix",
        "id": 1263,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Austrian Grand Prix",
        "id": 1264,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "British Grand Prix",
        "id": 1265,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Belgian Grand Prix",
        "id": 1266,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Sprint Qualifying", "url_suffix": "sprint-qualifying"},
            {"type": "Sprint", "url_suffix": "sprint"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Hungarian Grand Prix",
        "id": 1267,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Dutch Grand Prix",
        "id": 1268,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Italian Grand Prix",
        "id": 1269,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Azerbaijan Grand Prix",
        "id": 1270,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Singapore Grand Prix",
        "id": 1271,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "United States Grand Prix",
        "id": 1272,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Sprint Qualifying", "url_suffix": "sprint-qualifying"},
            {"type": "Sprint", "url_suffix": "sprint"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Mexico City Grand Prix",
        "id": 1273,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Brazilian Grand Prix",
        "id": 1274,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Sprint Qualifying", "url_suffix": "sprint-qualifying"},
            {"type": "Sprint", "url_suffix": "sprint"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Las Vegas Grand Prix",
        "id": 1275,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
    {
        "name": "Abu Dhabi Grand Prix",
        "id": 1276,
        "events": [
            {"type": "Free Practice 1", "url_suffix": "practice/1"},
            {"type": "Free Practice 2", "url_suffix": "practice/2"},
            {"type": "Free Practice 3", "url_suffix": "practice/3"},
            {"type": "Qualifying", "url_suffix": "qualifying"},
            {"type": "Grand Prix", "url_suffix": "race-result"},
        ],
    },
]